# Generated by Django 3.2.8 on 2021-11-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='img_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
